# Generated by Django 3.0.7 on 2020-06-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='interst',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='country',
            new_name='region',
        ),
    ]
